apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: ms-generator
  labels:
    cloud.googleapis.com/location: asia-south1
  annotations:

spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '3'
    spec:
      serviceAccountName: ms-generator
      containerConcurrency: 80
      timeoutSeconds: 300
      containers:
        - image: gcr.io/gh-erp-project-3612/ms-generator:latest
          resources:
            limits:
              cpu: 1000m
              memory: 256Mi
          #volumeMounts:
            #- name: generated-data
              #mountPath: /rootdir
     
      #volumes:
         #- name: generated-data
           #emptyDir: {}
         
  traffic:
    - percent: 100
      latestRevision: true