---
apiVersion: v1
kind: Service
metadata:
  name: ms-generator-service-svc
  labels:
    app: ms-generator-service-app
spec:
  type: LoadBalancer
  selector:
    app: ms-generator-service-app
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
